'use strict';

export const jsonError = {
  1000: 'Invalid credential',
  1001: 'Malformed request',
  1002: 'Need accept CGU',
  1003: 'Incorrect username',
  1004: 'Incorrect email',
  1006: 'Incorrect password',
  1007: 'Too user has this username',
  1008: 'Duplicate data',
  1009: 'Unknown user',
  1010: 'Only users can use this endpoint',
  1011: 'Need credential for this endpoint',
};

export const genresKey = [
  'action',
  'martial_arts',
  'adventure',
  'comedy',
  'deamon',
  'detective',
  'drama',
  'fantasy',
  'game',
  'harem',
  'historical',
  'horror',
  'magical_girl',
  'magic',
  'mecha',
  'cop',
  'post_apocalyptic',
  'romance',
  'school',
  'sci_fi',
  'steampunk',
  'surnatural',
  'thriller',
  'slice_of_life',
  'uchrony',
  'vampire',
  'war',
  'yuri',
  'yaoi',
  'sport',
  'space',
  'ecchi',
];
